source 'https://github.com/ietstudio/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Facebook_Example', :exclusive => true do
  pod "Facebook", :path => "../"
end

target 'Facebook_Tests', :exclusive => true do
  pod "Facebook", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
